### ISSUE TITLE
在我的红米手机中需要修改二个地方才能正常使用

### ISSUE THREAD

**Issue by guangchun** [lovetuzitong/MultiImageSelector#20]
1.修改MultiImageSelectorActivity.java文件中的onCameraShot(File imageFile)，加入以下一行代码用于通知系统跟新相册：
sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(imageFile)));// 刷新系统相册
修改后才能正常的从相册中看到刚拍的照片。
2.修改FileUtils.java
把File pic = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);这一行代码改成：
File pic = null;
pic = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM+ "/Camera");
if (!pic.exists()) {
    pic = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM);
}
才能正确的把照片保存到系统相册中。

**Comment by huangjr21** [comment]
谢谢，我用的是小米手机，遇到的问题和你差不多，用了你的方法解决了，再次感谢！

**Comment by lovetuzitong** [comment]
tks
