### ISSUE TITLE
您好,相关技术讨论

### ISSUE THREAD

**Issue by 13120241790** [lovetuzitong/MultiImageSelector#26]
1 看你图片加载用了 picasso  这里建议可以换成自己的加载类 这样别人集成您的这个图片加载框架不会对 APK 增量进行增大 :+1:  特别是 对于 SDK 开发 如果加了第三方导致别人用 picasso 的时候会造成多jar 冲突

2 :cn:  不知道您是不是 中国人 看得懂我写的不 因为看你代码里面写了很多中文注释 应该是中国的开发者吧 最新 我公司项目中 也需要开发了 多选相册 排序 预览 我都自己做完了 但是一直也有一些 bug 希望可以跟您 探讨一下 

3 我看还一些拍照的朋友唤起相机就 crash 了  应该是 某些机型 rom 太小  唤起相机就把底下栈的资源回收了  导致的这个情况

 比如我目前是 判断 jpg jepg bmp png 结尾字符串来获取 uri  但是 有的图片其实是损坏了的 这样加载出来就是 白色  而且我在后期已经做了 图片多选预览功能  也可以 pull request 整合到您的项目里面

希望能获得您的联系方式  
  QQ: 623414533
TEL : 13120241790
 EMAIL: 13120241790@163.com
:ghost:   Thanks

**Comment by 282144757** [comment]
你的预览功能添加了没有啊，加上预览后，这个项目就完整了。
