### ISSUE TITLE
Override My AppName,what's the happed?

### ISSUE THREAD

**Issue by Talbot3** [lovetuzitong/MultiImageSelector#28]
# Override My AppName,what's the happed?

> when i add code follow with you  Readme to my project ,
> I find a amazing thing My app name became to be a '多图选择器‘，this is a bug,How auto become User's project name?this is a problem

**Comment by yukuoyuan** [comment]
speak  chinese    OK？？

--- 原始邮件 ---

发件人： "orangebook" notifications@github.com
已发： 2015年9月19日 下午4:03
收件人： "lovetuzitong/MultiImageSelector" MultiImageSelector@noreply.github.com
主题： [MultiImageSelector] Override My AppName,what's the happed? (#28)

#Override My AppName,what's the happed?

> when i add code follow with you  Readme to my project ,
> I find a amazing thing My app name became to be a '多图选择器‘，this is a bug,How auto become User's project name?this is a problem

---

Reply to this email directly or view it on GitHub:
https://github.com/lovetuzitong/MultiImageSelector/issues/28

**Comment by yyshiningyear** [comment]
you can delete the app_name in values/string.xml (both en and zh)
