### ISSUE TITLE
当添加依赖时，APP_Name被覆盖了，使用时删除APP_Name即可Override My AppName,what's the happed?

### ISSUE THREAD

**Issue by Talbot3** [lovetuzitong/MultiImageSelector#29]
> when i add code follow with you  Readme to my project ,
> I find a amazing thing My app name became to be a '多图选择器‘，this is a bug,How auto become User's project name?this is a problem

**Comment by hexianqiao3755** [comment]
+1我也遇到了这个问题 求解决方案

**Comment by lovetuzitong** [comment]
最新版 [v1.1](https://github.com/lovetuzitong/MultiImageSelector/releases/tag/1.1) 还有这个问题么？可以发一下你的测试代码到我邮箱？ @hexianqiao3755

**Comment by hexianqiao3755** [comment]
我用的就是1.1版本的, 没有测试代码 就是简单集成了一下,  自己app的名字就变成了'多图选择器', 都没办法改回来

**Comment by lovetuzitong** [comment]
@hexianqiao3755 
`v1.1` 整个项目里面都没有 `多图选择器` 这几个中文字... 
`多图选择` 这几个中文字倒是有，但他是 `app` 这个module的，不是库 `multi-image-selector` ....

**Comment by hexianqiao3755** [comment]
在资源文件values-zh里面
<string name="app_name">多图选择器</string>

**Comment by lovetuzitong** [comment]
抱歉，这个问题你可以依赖直接依赖 `master/multi-image-selector` 来解决。 
`v1.1` 确实存在这个问题。

**Comment by hexianqiao3755** [comment]
请问这个问题下个版本可以解决吗, 我不想项目依赖一大堆liblibrary

**Comment by lovetuzitong** [comment]
好吧，我打了个tag, 依赖版本换成 `1.2` 即可

**Comment by hexianqiao3755** [comment]
好的, 谢谢
