### ISSUE TITLE
MultiImageSelectorActivity执行finish后内存无法释放！MAT工具显示Picasso内部的线程一直持有MultiImageSelectorActivity，导致无法释放

### ISSUE THREAD

**Issue by logerr** [lovetuzitong/MultiImageSelector#32]
MultiImageSelectorActivity执行finish后内存无法释放！MAT工具显示Picasso内部的Dispatcher线程一直持有MultiImageSelectorActivity，而且这个Dispatcher线程一直长期运行，导致无法释放内存。
只要把Picasso.shutdown就行了。

**Comment by taoranziwangji** [comment]
没效果啊 而且直接调用静态方法会报错
