### ISSUE TITLE
Shoundn't choice the camera when pic number is max.

### ISSUE THREAD

**Issue by feaoes** [lovetuzitong/MultiImageSelector#33]
呵呵。才发现原来里面是中文注释。。
选择相机的时候，当图片数量为最大时，不应该能够点击拍照了。应该提示已经到达最大数量。
这样比较合理。

**Comment by memorytale** [comment]
@feaoes 针对这个问题，我在MultiImageSelectorFragment的showCameraAction方法里修改了一下，就可以避免这个问题了，修改如下：
 /**
     \* 选择相机
     */
    private void showCameraAction() {
        if (resultList.size() == mDesireImageCount) {
            Toast.makeText(getActivity(), R.string.msg_amount_limit, Toast.LENGTH_SHORT).show();
            return;
        }
        // 跳转到系统照相机
        Intent cameraIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        if (cameraIntent.resolveActivity(getActivity().getPackageManager()) != null) {
            // 设置系统相机拍照后的输出路径
            // 创建临时文件
            mTmpFile = FileUtils.createTmpFile(getActivity());
            cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(mTmpFile));
            startActivityForResult(cameraIntent, REQUEST_CAMERA);
        } else {
            Toast.makeText(getActivity(), R.string.msg_no_camera, Toast.LENGTH_SHORT).show();
        }
    }
