### ISSUE TITLE
大量图片不显示

### ISSUE THREAD

**Issue by lyzcom** [lovetuzitong/MultiImageSelector#40]
使用新版Picasso后大量图片不显示。v2.5.2
![s60104-235418](https://cloud.githubusercontent.com/assets/6939707/12093859/5011bc70-b340-11e5-9f2c-4dd2e6cdef3d.jpg)

**Comment by lyzcom** [comment]
设备： mx4，mx5

**Comment by lyzcom** [comment]
Picasso 低版本与 okhttp冲突，新版本大量图片不显示

**Comment by jolly336** [comment]
我也遇到了，现在只能用Picasso的v2.4.0版本了，2.5.2有点问题，用UIL和Fresco都可以的

**Comment by lovetuzitong** [comment]
Picasso 2.5+ 在decodeStream 有点问题。暂时解决的话可以修改BitmapHunter的markPosition数值。

**Comment by fflamingogo** [comment]
我直接换了Ficasso了

**Comment by jolly336** [comment]
关于Picasso 2.5+在decodeStream上的问题，有修复完可以参考的例子吗？谢谢！
