### ISSUE TITLE
switch back to browse all will show camera grid no matter what

### ISSUE THREAD

**Issue by liuxu0703** [lovetuzitong/MultiImageSelector#5]
when switch to browse another folder, and then switch back to browse all images,
the camera grid will be shown regardless of whether the camera is requested.

solution is simple:

@@ -271,7 +273,9 @@ public class MultiImageSelectorFragment extends Fragment {
                 if (i == 0) {
                     getActivity().getSupportLoaderManager().restartLoader(LOADER_ALL, null, mLoaderCallback);
                     mCategoryText.setText(R.string.folder_all);
 --                    mImageAdapter.setShowCamera(true);
 ++                    if (mIsShowCamera) {
 ++                        mImageAdapter.setShowCamera(true);
 ++                    }
                 } else {
                     Folder folder = (Folder) adapterView.getAdapter().getItem(i);
                     if (null != folder) {

@lovetuzitong wish you consider this~.

**Comment by lovetuzitong** [comment]
Thanks! :+1:
