### ISSUE TITLE
Step 0

### ISSUE THREAD

**Issue by drchopper** [lovetuzitong/MultiImageSelector#56]
Hello ,
"Step 0 Add module multi-image-selector as your dependence "--> What i have to do? Pls help!

```
repositories {
    maven { url "https://jitpack.io" }

}

dependencies {
    compile 'com.github.lovetuzitong:multi-image-selector'
}
```

doesn't work!

**Comment by lovetuzitong** [comment]
Download the repo, import module, set as dependence.
Add the following line 
`compile project(':multi-image-selector')`
into your `build.gradle` file `dependencies` block
