### ISSUE TITLE
6.0问题

### ISSUE THREAD

**Issue by FENG-MASTER** [lovetuzitong/MultiImageSelector#64]
6.0的机子运行的时候,就算添加了权限也会报错,无权限

**Comment by vihuela** [comment]
它逻辑在Fragment上，replace之前需要判断权限即可

**Comment by logerr** [comment]
具体是什么机器  日志是什么？

**Comment by lovetuzitong** [comment]
参见[Android M 运行时权限](https://developer.android.com/training/permissions/index.html). 具体使用可以checkout最新demo

**Comment by SomnusWu** [comment]
MultiImageSelectorFragment   showCameraAction() 方法中 没有对 CAMERA  权限进行处理 6.0
