### ISSUE TITLE
picasso升级后部分图片加载不了

### ISSUE THREAD

**Issue by myloften** [lovetuzitong/MultiImageSelector#65]
picasso升级后稍大的图显示不了

**Comment by ho2xing** [comment]
1，将现有的picasso版本升级为：com.squareup.picasso:picasso:2.6.0-SNAPSHOT 可以解决。
2，另可修改资源文件名称，防止资源合并时候名称冲突，导致不可预料的问题。

**Comment by myloften** [comment]
@ho2xing 可以了，谢谢
