### ISSUE TITLE
更新以后 ，拉取不下来了   

### ISSUE THREAD

**Issue by fengxiaowei** [lovetuzitong/MultiImageSelector#70]
Error:(48, 13) Failed to resolve: com.github.lovetuzitong:MultiImageSelector:1.1

**Comment by Isabellle** [comment]
Works fine if you add it as a module within Android Studio and then `compile project(":multi-image-selector")` in your Gradle

**Comment by fengxiaowei** [comment]
Error:Failed to resolve: com.android.support:appcompat-v7:23.4.0
