### ISSUE TITLE
请问aar包中，如何包含第三方依赖库

### ISSUE THREAD

**Issue by xymelon** [lovetuzitong/MultiImageSelector#76]
比如配置你的项目，只需compile就能包含picasso库，如下：
`compile 'com.github.lovetuzitong:MultiImageSelector:1.1'`
而不再引用
`compile 'com.squareup.picasso:picasso:2.4.0'`
而且我看还不包含AndroidManifest.xml....
这是怎么做的？谢谢

**Comment by lovetuzitong** [comment]
[build.gradle](https://github.com/lovetuzitong/MultiImageSelector/blob/master/multi-image-selector/build.gradle)

``` java
dependencies {
    //...
    compile 'com.squareup.picasso:picasso:2.4.0'
}
```

**Comment by xymelon** [comment]
额 这说明了什么 还是没懂 还请赐教
目前我的module也这么配置的，如下，然后生成了aar包

```
dependencies {
    //....
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile 'io.reactivex:rxandroid:1.2.0'
    compile 'io.reactivex:rxjava:1.1.5'
}
```

但是在另外的项目直接引用compile 'xxx:1.0.0'时，还是会找不到module依赖的这些包，比如rxjava

**Comment by lovetuzitong** [comment]
1. 尝试重新rebuild整个项目试试，不行看 2
2. 尝试直接作为module依赖，如果可以找到依赖包，说明module没问题。如果作为库依赖找不到依赖包，说明库打包姿势有问题。
3. 关于Gradle的依赖，可以参考 [Dependency Management Basics](https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html)

**Comment by autoool** [comment]
@cowfighting 如果直接作为module 依赖是没有问题的，但是如果打包成aar，确实找不到相关的类。
很久也没有找到方法。

**Comment by Michael-DJI** [comment]
给你举个例子：
compile ('net.zetetic:android-database-sqlcipher:3.5.7@aar') {
        transitive = true
}
加上这个transitive属性，你的依赖就可以传递出去了

**Comment by omgseven** [comment]
compile 'com.github.lovetuzitong:MultiImageSelector:1.1'
你是以这种方式依赖MultiImageSelector，而MultiImageSelector又以相同方式依赖Picasso，所以打包的MultiImageSelector中并没有打包Picasso，而是在依赖期间根据依赖关系自动下载Picasso的。
